### PR TITLE
Issue/accessibility

### PR DESCRIPTION
**Pull request by cayb0rg**
This addresses keyboard navigation and screenreader accessibility issues in the Player. 

Problem | Action | Completed
-- | -- | --
Tutorial modal doesn't have initial focus. | Add role="alertdialog", aria-labelledby, aria-describedby and somehow change focus to the modal, possibly by moving it to the top of the DOM and hiding the other content until "Got It" is pressed. | Yes
Button functionality strictly limited to mouse interactions. | Appears to be using the library Hammer for button events. Event "tap" is not fired when clicked.  Add ``onClick`` and keyboard events to buttons. | Yes
Can use tab navigation to see flashcards not in frame, including the back of cards when front is being shown. | Remove flashcards from tab order, add aria-hidden to opposite side of card, add aria-label to flashcards  | Yes
Similar to the problem above. Flashcards require multiple key presses to navigate and read before proceeding in VoiceOver | Either minimize the number of keypresses or remove them altogether by assigning an aria-label to the flashcard parent element that reads out the card's contents. | Former option
Using ``<div>``'s for buttons and other HTML semantic elements. | Use HTML semantics and aria-roles. | Yes
Arrow keys are being to move between flash cards, but this key is used by VoiceOver for navigating. | Make left and right arrow buttons easily navigable. New/additional key bindings: S (discard), A (left card), D (right card), W (un-discard) | Yes
Images don't have descriptions | Add the alt attribute to images | Yes
Instructions rely on visual aids. | Make instructions universal. | Partial
Color contrast ratio is 1.61:1 | Make color contrast ratio 4.5:1 to meet WCAG AA for Normal Text. | Yes
Discard pile's tab index is the same placement as it was in the flashcards. This could pose an issue with large numbers of flashcards. | Remove and add the flashcard to a separate DOM element. Perform the reverse for undiscard. | Yes

(**Update**: See below!) One outstanding issue that I'm still struggling with is that flashcards are being treated as "groups". Sometimes the user must navigate backwards to read the card's contents (e.g. when they click the Next Card arrow). I'm not sure if this is something that's normal or that should be replaced with an overarching aria-label on the parent flashcard.

### **Update**
There are two versions for testing. The latest commit makes flashcards a single aria label. To test the other version run ``git checkout 18af1c51f9c33a777d8a60d2ae86de2252b6347d``.

### CODE REVIEW

**Review by FrenjaminBanklin — COMMENTED** [review]
Keyboard interactivity seems to be pretty good, and Voiceover seems to handle it well for the most part, though there may be some additional improvements made there.

Other things I can think of potentially trying to do:

- After 'clicking' the 'Got it!' button in the intro screen, nothing really has focus. Pressing the Tab key at this point goes to the 'Help' button which is fine, but it may be better to auto-focus something once the intro dialog is closed. Either the help button since that's the next thing in the natural tab order, or the front face of the first card.
- The 'Previous card' button is still reachable in the tab order even on the first card, and the  'Next card' button is still reachable in the tab order even on the last card. Trying to click them/pressing space/pressing enter/return does nothing. It might make sense to leave them there so the layout remains predictable, but we should try do clarify to the screen reader that they don't do anything - maybe have it read out 'disabled' or something.
- My first instinct, without seeing the 'help' menu, is to press the space bar or enter on a card to flip it.
- There doesn't seem to be any way of making the screen reader re-read the current card face short of tabbing to something else and then tabbing back to the card. It might be nice to have a dedicated key to re-read the card.
  - Likewise when a card is flipped, the screen reader doesn't automatically read the new face. Users have to tab away and then tab back into the card to read the new face after flipping a card.
- None of the explanatory text in the help menu is reachable with the tab key and none of the key bindings are read out by the screen reader. It may make sense to set the aria-label value of the help button to just read out all of the key bindings so an unsighted user can tab to the help button, listen to the instructions, and then tab away without having to open anything. Otherwise, maybe separate the normal interactive area from a 'help' area where everything is tab-reachable, and render one or the other inert based on whether or not the help menu is open.
- The help menu makes no mention of the actions tied to the arrow keys.
- This is more a nitpick than a problem, but: from the card face, the 'Previous card' button is reachable with a single shift-tab, but the 'Next card' button is two tabs away because the 'Discard' button comes first. I can see this making sense, but I wonder if it'd be better to swap the positions of these two buttons.
- This is not part of the accessibility fixes, but: the vocabulary of the 'rotate cards' button is weird. The verb for turning the card over is 'flip', so I'd expect the button that does it to all of them to read 'flip cards' rather than 'rotate cards'.
- When discarding (or restoring) a card,  the next card starts to be read and then the screen reader quickly stops to read 'Discarded/Undiscarded card' instead. In the case of discarding this only seems to happen the first time, and then discarding further cards doesn't read 'Discarded card' at all. It seems like this happens every time a card is restored. Not sure the best way of handling this, possibly automatically moving focus around a few aria-polite elements in a row to first indicate that a card was discarded and then re-focus on the new card so it reads properly?
  - Also, should probably have the screen reader say 'Restored card' rather than 'undiscarded card'.

**Comment by cayb0rg** [comment]
Thank you for the feedback! Realizing that I geared my changes towards an older version of Firefox, so they don't work on the latest Chrome and probably not the latest Firefox 🤦🏻

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
Phenomenal work. Keyboard control is intuitive. Screenreader support is outstanding. The live region updates are great.

The only thing I'm noticing to address: the player assumes the existence of the alt text property, which won't exist for previously created qsets. Right now it appears to just set the asset's alt text to "undefined", but that's a little confusing, and should probably be handled more gracefully.

**Comment by FrenjaminBanklin** [comment]
My approach in Enigma when missing alt text is to default to 'undescribed image'. I'm not sure if that's good practice to begin with, but we may want to standardize across all the widgets on some reasonable default for un-alt-texted images.

**Comment by cayb0rg** [comment]
* Changed empty alt text to "[Asset type] asset: Undescribed"
* Audio and video assets are now interactable
* Added current card info to aria-live update after shuffling and flipping cards
* Fixed variable naming (what is considered "back" and "front" are now the same as the creator)

To-Do: Other flash cards are tabbable again, oops

**Review by clpetersonucf — CHANGES_REQUESTED** [review]
Just two small things I noticed regarding alt text fallback.

As a side note, video may technically be supported but the media importer itself doesn't provide video embed support. That's currently handled on the widget side (see This or That or Adventure as examples). That can be handled separately, it's well beyond the scope of this branch.

**Review by clpetersonucf — APPROVED** [review]
All issues addressed. LGTM.

**Pull request merged**
